// This file is generated by Simplicity Studio.  Please do not edit manually.
//
//

// Enclosing macro to prevent multiple inclusion
#ifndef __SI_BOOTLOADER_CONFIG__
#define __SI_BOOTLOADER_CONFIG__


#define BTL_PLUGIN_STORAGE_NUM_SLOTS (2)

#define BTL_PLUGIN_STORAGE_SLOTS  \
  {\
    {8192, 258048}, /* Slot 0 */ \
    {266240, 258048}, /* Slot 1 */ \
  }\

// Number of slots in bootload list
#define BTL_STORAGE_BOOTLOAD_LIST_LENGTH BTL_PLUGIN_STORAGE_NUM_SLOTS

// Location of Bootload Info struct (used if there is more than 1 slot)
#define BTL_STORAGE_BOOTLOAD_INFO_ADDRESS (0)

#endif // __SI_BOOTLOADER_CONFIG__
